---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "install dependencies"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: present
    update_cache: yes

- name: "install pm2"
  shell: npm install pm2 -g

- name: "Creates directory"
  file:
    path: ~/web
    state: directory

- name: "copy index text page"
  copy:
    src: index.js
    dest: ~/web/
    backup: yes

- name: "start server"
  shell: pm2 start ~/web/index.js -f